import Landing from '@/components/Landing';
import LandingLayout from '@/components/layouts/LandingLayout';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Facial Recognition</title>

        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Landing />
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <LandingLayout>{page}</LandingLayout>;
};
